language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_script:
  - npm install -g netlify-cli phantomjs-prebuilt resume-cli jsonresume-theme-elegant
script:
  - resume export resume.json --theme elegant --format pdf
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  on:
    branch: master
env:
  - CI=true
